"""Playwright test for IOC extraction behavior verification."""

import pytest
from playwright.sync_api import Page, expect
import time
import json

class TestIOCExtractionBehavior:
    """Test IOC extraction behavior and field name fixes."""
    
    @pytest.fixture(autouse=True)
    def setup(self, page: Page):
        """Setup for each test - navigate to articles page."""
        page.goto("http://localhost:8001/articles")
        page.wait_for_load_state("networkidle")
        
        # Wait for articles to load
        page.wait_for_selector("table tbody tr", timeout=10000)
    
    def test_ioc_extraction_button_behavior(self, page: Page):
        """Test that Extract IOCs button works correctly."""
        # Find the first article row
        first_article = page.locator("table tbody tr").first
        expect(first_article).to_be_visible()
        
        # Click on the article to go to detail page
        first_article.click()
        page.wait_for_load_state("networkidle")
        
        # Wait for the article detail page to load
        expect(page.locator("h1")).to_be_visible()
        
        # Look for the Extract IOCs button
        extract_button = page.locator("button:has-text('Extract IOCs'), button:has-text('Display IOCs')")
        expect(extract_button).to_be_visible()
        
        # Click the Extract IOCs button
        extract_button.click()
        
        # Wait for the IOC modal to appear
        ioc_modal = page.locator("#iocsModal")
        expect(ioc_modal).to_be_visible(timeout=10000)
        
        # Check that the modal shows the correct generation info
        generation_info = page.locator("text=Generated by:")
        expect(generation_info).to_be_visible()
        
        # Verify that if LLM validation is not used, it doesn't show "(LLM Validated)"
        llm_validated_text = page.locator("text=(LLM Validated)")
        if llm_validated_text.is_visible():
            # If it shows LLM Validated, check if the checkbox is checked
            llm_checkbox = page.locator("#llmValidationToggle")
            if llm_checkbox.is_visible():
                is_checked = llm_checkbox.is_checked()
                if not is_checked:
                    pytest.fail("Modal shows '(LLM Validated)' but checkbox is unchecked - this is the bug!")
        
        # Close the modal
        close_button = page.locator("button:has-text('Close')")
        close_button.click()
        
        # Verify modal is closed
        expect(ioc_modal).not_to_be_visible()
    
    def test_ioc_regenerate_button_behavior(self, page: Page):
        """Test that Regenerate button works correctly."""
        # Find the first article row
        first_article = page.locator("table tbody tr").first
        expect(first_article).to_be_visible()
        
        # Click on the article to go to detail page
        first_article.click()
        page.wait_for_load_state("networkidle")
        
        # Wait for the article detail page to load
        expect(page.locator("h1")).to_be_visible()
        
        # Look for the Extract IOCs button and click it
        extract_button = page.locator("button:has-text('Extract IOCs'), button:has-text('Display IOCs')")
        expect(extract_button).to_be_visible()
        extract_button.click()
        
        # Wait for the IOC modal to appear
        ioc_modal = page.locator("#iocsModal")
        expect(ioc_modal).to_be_visible(timeout=10000)
        
        # Check the LLM validation checkbox state
        llm_checkbox = page.locator("#llmValidationToggle")
        if llm_checkbox.is_visible():
            initial_state = llm_checkbox.is_checked()
            
            # Toggle the checkbox
            llm_checkbox.click()
            new_state = llm_checkbox.is_checked()
            
            # Verify state changed
            assert initial_state != new_state, "Checkbox state should have changed"
        
        # Click the Regenerate button
        regenerate_button = page.locator("button:has-text('Regenerate')")
        expect(regenerate_button).to_be_visible()
        regenerate_button.click()
        
        # Wait for the loading modal to appear
        loading_modal = page.locator("#loadingModal")
        expect(loading_modal).to_be_visible(timeout=5000)
        
        # Wait for loading to complete (this might take a while)
        expect(loading_modal).not_to_be_visible(timeout=60000)
        
        # The modal should still be visible after regeneration
        expect(ioc_modal).to_be_visible()
        
        # Close the modal
        close_button = page.locator("button:has-text('Close')")
        close_button.click()
        
        # Verify modal is closed
        expect(ioc_modal).not_to_be_visible()
    
    def test_ioc_field_name_consistency(self, page: Page):
        """Test that IOC field names are consistent between display and data."""
        # Find the first article row
        first_article = page.locator("table tbody tr").first
        expect(first_article).to_be_visible()
        
        # Click on the article to go to detail page
        first_article.click()
        page.wait_for_load_state("networkidle")
        
        # Wait for the article detail page to load
        expect(page.locator("h1")).to_be_visible()
        
        # Look for the Extract IOCs button and click it
        extract_button = page.locator("button:has-text('Extract IOCs'), button:has-text('Display IOCs')")
        expect(extract_button).to_be_visible()
        extract_button.click()
        
        # Wait for the IOC modal to appear
        ioc_modal = page.locator("#iocsModal")
        expect(ioc_modal).to_be_visible(timeout=10000)
        
        # Check the generation info text
        generation_info = page.locator("text=Generated by:")
        expect(generation_info).to_be_visible()
        
        # Get the full text of the generation info
        generation_text = generation_info.text_content()
        
        # Check if LLM validation checkbox is visible and its state
        llm_checkbox = page.locator("#llmValidationToggle")
        if llm_checkbox.is_visible():
            is_checked = llm_checkbox.is_checked()
            
            # If checkbox is checked, should show "(LLM Validated)"
            if is_checked:
                assert "(LLM Validated)" in generation_text, f"Expected '(LLM Validated)' in text when checkbox is checked. Got: {generation_text}"
            else:
                assert "(LLM Validated)" not in generation_text, f"Expected no '(LLM Validated)' in text when checkbox is unchecked. Got: {generation_text}"
        
        # Close the modal
        close_button = page.locator("button:has-text('Close')")
        close_button.click()
        
        # Verify modal is closed
        expect(ioc_modal).not_to_be_visible()
