"""Test IOC regenerate functionality with Playwright."""

import pytest
from playwright.sync_api import Page, expect
import time

def test_ioc_regenerate_functionality(page: Page):
    """Test IOC regenerate functionality and LLM validation toggle."""
    # Navigate directly to article 2175
    page.goto("http://localhost:8001/articles/2175")
    page.wait_for_load_state("networkidle")
    
    print(f"Page title: {page.title()}")
    print(f"Page URL: {page.url}")
    
    # Click on the AI/ML Assistant button
    ai_assistant_button = page.locator("button:has-text('AL/ML Assistant')")
    if ai_assistant_button.is_visible():
        print("Found AI/ML Assistant button, clicking it")
        ai_assistant_button.click()
        
        # Wait for AI assistant modal
        ai_modal = page.locator("#aiAssistantModal")
        if ai_modal.is_visible(timeout=5000):
            print("AI Assistant modal opened")
            
            # Click the Display IOCs button
            display_ioc_button = page.locator("button:has-text('Display IOCs')")
            if display_ioc_button.is_visible():
                print("Found Display IOCs button, clicking it")
                display_ioc_button.click()
                
                # Wait for IOC modal
                ioc_modal = page.locator("#iocsModal")
                if ioc_modal.is_visible(timeout=10000):
                    print("IOC modal opened")
                    page.screenshot(path="ioc_modal_initial.png")
                    
                    # Check initial state
                    generation_info = page.locator("text=Generated by:")
                    if generation_info.is_visible():
                        initial_generation_text = generation_info.text_content()
                        print(f"Initial generation info: {initial_generation_text}")
                        
                        # Check LLM validation checkbox
                        llm_checkbox = page.locator("#llmValidationToggle")
                        if llm_checkbox.is_visible():
                            initial_checkbox_state = llm_checkbox.is_checked()
                            print(f"Initial LLM checkbox state: {initial_checkbox_state}")
                            
                            # Test 1: Toggle checkbox and regenerate
                            print("\n=== Test 1: Toggle checkbox and regenerate ===")
                            llm_checkbox.click()
                            new_checkbox_state = llm_checkbox.is_checked()
                            print(f"Toggled LLM checkbox to: {new_checkbox_state}")
                            
                            # Click regenerate
                            regenerate_button = page.locator("button:has-text('Regenerate')")
                            if regenerate_button.is_visible():
                                print("Found Regenerate button, clicking it")
                                regenerate_button.click()
                                
                                # Wait for loading modal
                                loading_modal = page.locator("#loadingModal")
                                if loading_modal.is_visible(timeout=5000):
                                    print("Loading modal appeared")
                                    # Wait for loading to complete
                                    expect(loading_modal).not_to_be_visible(timeout=60000)
                                    print("Loading completed")
                                    
                                    # Check the generation info after regeneration
                                    generation_info = page.locator("text=Generated by:")
                                    if generation_info.is_visible():
                                        new_generation_text = generation_info.text_content()
                                        print(f"New generation info: {new_generation_text}")
                                        
                                        # Verify the logic after regeneration
                                        if new_checkbox_state and "(LLM Validated)" not in new_generation_text:
                                            print("ERROR: After regeneration, checkbox is checked but no LLM Validated text!")
                                            assert False, "After regeneration, checkbox is checked but no LLM Validated text!"
                                        elif not new_checkbox_state and "(LLM Validated)" in new_generation_text:
                                            print("ERROR: After regeneration, checkbox is unchecked but shows LLM Validated text!")
                                            assert False, "After regeneration, checkbox is unchecked but shows LLM Validated text!"
                                        else:
                                            print("SUCCESS: Display logic is correct after regeneration!")
                                        
                                        page.screenshot(path="ioc_modal_after_regenerate.png")
                                        
                                        # Test 2: Toggle back and regenerate again
                                        print("\n=== Test 2: Toggle back and regenerate again ===")
                                        llm_checkbox.click()
                                        final_checkbox_state = llm_checkbox.is_checked()
                                        print(f"Toggled LLM checkbox to: {final_checkbox_state}")
                                        
                                        regenerate_button.click()
                                        
                                        # Wait for loading again
                                        if loading_modal.is_visible(timeout=5000):
                                            print("Loading modal appeared again")
                                            expect(loading_modal).not_to_be_visible(timeout=60000)
                                            print("Loading completed again")
                                            
                                            # Check final state
                                            generation_info = page.locator("text=Generated by:")
                                            if generation_info.is_visible():
                                                final_generation_text = generation_info.text_content()
                                                print(f"Final generation info: {final_generation_text}")
                                                
                                                # Verify final logic
                                                if final_checkbox_state and "(LLM Validated)" not in final_generation_text:
                                                    print("ERROR: Final state - checkbox is checked but no LLM Validated text!")
                                                    assert False, "Final state - checkbox is checked but no LLM Validated text!"
                                                elif not final_checkbox_state and "(LLM Validated)" in final_generation_text:
                                                    print("ERROR: Final state - checkbox is unchecked but shows LLM Validated text!")
                                                    assert False, "Final state - checkbox is unchecked but shows LLM Validated text!"
                                                else:
                                                    print("SUCCESS: Final display logic is correct!")
                                                
                                                page.screenshot(path="ioc_modal_final.png")
                                        
                                        # Close modal
                                        close_button = page.locator("button:has-text('Close')")
                                        if close_button.is_visible():
                                            close_button.click()
                                            print("IOC modal closed")
                                    else:
                                        print("Generation info not found after regeneration")
                                else:
                                    print("Loading modal did not appear")
                            else:
                                print("Regenerate button not found")
                        else:
                            print("LLM checkbox not found")
                    else:
                        print("Generation info not found")
                else:
                    print("IOC modal did not open")
            else:
                print("Display IOCs button not found")
        else:
            print("AI Assistant modal did not open")
    else:
        print("AI/ML Assistant button not found")
    
    # Test passed if we get here
    assert True
