"""Simple Playwright test to verify IOC extraction behavior."""

import pytest
from playwright.sync_api import Page, expect
import time

def test_ioc_extraction_behavior_simple(page: Page):
    """Simple test to verify IOC extraction behavior."""
    # Navigate to articles page
    page.goto("http://localhost:8001/articles")
    page.wait_for_load_state("networkidle")
    
    # Take a screenshot to see what's on the page
    page.screenshot(path="articles_page.png")
    
    # Print page title and content
    print(f"Page title: {page.title()}")
    print(f"Page URL: {page.url}")
    
    # Check if there are any articles
    articles_table = page.locator("table")
    if articles_table.is_visible():
        print("Articles table found")
        # Look for article rows
        article_rows = page.locator("table tbody tr")
        article_count = article_rows.count()
        print(f"Found {article_count} articles")
        
        if article_count > 0:
            # Click on the first article
            first_article = article_rows.first
            first_article.click()
            page.wait_for_load_state("networkidle")
            
            # Take screenshot of article detail page
            page.screenshot(path="article_detail.png")
            print(f"Navigated to article detail page: {page.url}")
            
            # Look for Extract IOCs button
            extract_button = page.locator("button:has-text('Extract IOCs'), button:has-text('Display IOCs')")
            if extract_button.is_visible():
                print("Found Extract IOCs button")
                extract_button.click()
                
                # Wait for modal
                ioc_modal = page.locator("#iocsModal")
                if ioc_modal.is_visible(timeout=10000):
                    print("IOC modal opened")
                    page.screenshot(path="ioc_modal.png")
                    
                    # Check generation info
                    generation_info = page.locator("text=Generated by:")
                    if generation_info.is_visible():
                        generation_text = generation_info.text_content()
                        print(f"Generation info: {generation_text}")
                        
                        # Check if LLM validation checkbox is visible
                        llm_checkbox = page.locator("#llmValidationToggle")
                        if llm_checkbox.is_visible():
                            is_checked = llm_checkbox.is_checked()
                            print(f"LLM checkbox checked: {is_checked}")
                            
                            # Verify the logic
                            if is_checked and "(LLM Validated)" not in generation_text:
                                print("ERROR: Checkbox is checked but no LLM Validated text!")
                                assert False, "Checkbox is checked but no LLM Validated text!"
                            elif not is_checked and "(LLM Validated)" in generation_text:
                                print("ERROR: Checkbox is unchecked but shows LLM Validated text!")
                                assert False, "Checkbox is unchecked but shows LLM Validated text!"
                            else:
                                print("SUCCESS: Display logic is correct!")
                        
                        # Close modal
                        close_button = page.locator("button:has-text('Close')")
                        if close_button.is_visible():
                            close_button.click()
                            print("Modal closed")
                else:
                    print("IOC modal did not open")
            else:
                print("Extract IOCs button not found")
        else:
            print("No articles found in table")
            # Let's try to create a test article or navigate to a specific article
            # Try navigating to article ID 2175 (from the user's image)
            page.goto("http://localhost:8001/articles/2175")
            page.wait_for_load_state("networkidle")
            page.screenshot(path="article_2175.png")
            print(f"Tried to navigate to article 2175: {page.url}")
            
            # Look for Extract IOCs button on this specific article
            extract_button = page.locator("button:has-text('Extract IOCs'), button:has-text('Display IOCs')")
            if extract_button.is_visible():
                print("Found Extract IOCs button on article 2175")
                extract_button.click()
                
                # Wait for modal
                ioc_modal = page.locator("#iocsModal")
                if ioc_modal.is_visible(timeout=10000):
                    print("IOC modal opened for article 2175")
                    page.screenshot(path="ioc_modal_2175.png")
                    
                    # Check generation info
                    generation_info = page.locator("text=Generated by:")
                    if generation_info.is_visible():
                        generation_text = generation_info.text_content()
                        print(f"Generation info: {generation_text}")
                        
                        # Check if LLM validation checkbox is visible
                        llm_checkbox = page.locator("#llmValidationToggle")
                        if llm_checkbox.is_visible():
                            is_checked = llm_checkbox.is_checked()
                            print(f"LLM checkbox checked: {is_checked}")
                            
                            # Verify the logic
                            if is_checked and "(LLM Validated)" not in generation_text:
                                print("ERROR: Checkbox is checked but no LLM Validated text!")
                                assert False, "Checkbox is checked but no LLM Validated text!"
                            elif not is_checked and "(LLM Validated)" in generation_text:
                                print("ERROR: Checkbox is unchecked but shows LLM Validated text!")
                                assert False, "Checkbox is unchecked but shows LLM Validated text!"
                            else:
                                print("SUCCESS: Display logic is correct!")
                        
                        # Close modal
                        close_button = page.locator("button:has-text('Close')")
                        if close_button.is_visible():
                            close_button.click()
                            print("Modal closed")
                else:
                    print("IOC modal did not open for article 2175")
            else:
                print("Extract IOCs button not found on article 2175")
    else:
        print("No articles table found")
    
    # Always pass the test for now - we're just debugging
    assert True
