"""Test IOC extraction behavior on specific article."""

import pytest
from playwright.sync_api import Page, expect
import time

def test_ioc_extraction_on_article_2175(page: Page):
    """Test IOC extraction behavior on article 2175."""
    # Navigate directly to article 2175
    page.goto("http://localhost:8001/articles/2175")
    page.wait_for_load_state("networkidle")
    
    # Take a screenshot to see what's on the page
    page.screenshot(path="article_2175_detail.png")
    
    print(f"Page title: {page.title()}")
    print(f"Page URL: {page.url}")
    
    # Look for Extract IOCs button with various possible text patterns
    extract_button = page.locator("button:has-text('Extract IOCs'), button:has-text('Display IOCs'), button:has-text('IOCs')")
    
    # Also try to find any button that might be related to IOCs
    all_buttons = page.locator("button")
    button_count = all_buttons.count()
    print(f"Found {button_count} buttons on the page")
    
    for i in range(button_count):
        button = all_buttons.nth(i)
        if button.is_visible():
            button_text = button.text_content()
            print(f"Button {i}: '{button_text}'")
    
    if extract_button.is_visible():
        print("Found Extract IOCs button")
        button_text = extract_button.text_content()
        print(f"Button text: {button_text}")
        
        extract_button.click()
    else:
        # Try clicking on the AI/ML Assistant button
        ai_assistant_button = page.locator("button:has-text('AL/ML Assistant'), button:has-text('AI/ML Assistant')")
        if ai_assistant_button.is_visible():
            print("Found AI/ML Assistant button, clicking it")
            ai_assistant_button.click()
            
            # Wait for AI assistant modal
            ai_modal = page.locator("#aiAssistantModal")
            if ai_modal.is_visible(timeout=5000):
                print("AI Assistant modal opened")
                page.screenshot(path="ai_assistant_modal.png")
                
                # Look for IOC-related buttons in the AI assistant modal
                ioc_buttons = page.locator("button:has-text('IOC'), button:has-text('Extract'), button:has-text('🔍')")
                ioc_button_count = ioc_buttons.count()
                print(f"Found {ioc_button_count} IOC-related buttons in AI modal")
                
                for i in range(ioc_button_count):
                    ioc_button = ioc_buttons.nth(i)
                    if ioc_button.is_visible():
                        button_text = ioc_button.text_content()
                        print(f"IOC Button {i}: '{button_text}'")
                
                # Try to find and click the Display IOCs button specifically
                extract_ioc_button = page.locator("button:has-text('Display IOCs')")
                if extract_ioc_button.is_visible():
                    print("Found IOC extraction button in AI modal")
                    extract_ioc_button.click()
                    
                    # Wait for IOC modal
                    ioc_modal = page.locator("#iocsModal")
                    if ioc_modal.is_visible(timeout=10000):
                        print("IOC modal opened from AI assistant")
                        page.screenshot(path="ioc_modal_from_ai.png")
                        
                        # Check generation info
                        generation_info = page.locator("text=Generated by:")
                        if generation_info.is_visible():
                            generation_text = generation_info.text_content()
                            print(f"Generation info: {generation_text}")
                            
                            # Check if LLM validation checkbox is visible
                            llm_checkbox = page.locator("#llmValidationToggle")
                            if llm_checkbox.is_visible():
                                is_checked = llm_checkbox.is_checked()
                                print(f"LLM checkbox checked: {is_checked}")
                                
                                # Verify the logic
                                if is_checked and "(LLM Validated)" not in generation_text:
                                    print("ERROR: Checkbox is checked but no LLM Validated text!")
                                    assert False, "Checkbox is checked but no LLM Validated text!"
                                elif not is_checked and "(LLM Validated)" in generation_text:
                                    print("ERROR: Checkbox is unchecked but shows LLM Validated text!")
                                    assert False, "Checkbox is unchecked but shows LLM Validated text!"
                                else:
                                    print("SUCCESS: Display logic is correct!")
                                
                                # Close IOC modal
                                close_button = page.locator("button:has-text('Close')")
                                if close_button.is_visible():
                                    close_button.click()
                                    print("IOC modal closed")
                            else:
                                print("LLM checkbox not found in IOC modal")
                        else:
                            print("Generation info not found in IOC modal")
                    else:
                        print("IOC modal did not open from AI assistant")
                else:
                    print("No IOC extraction button found in AI modal")
                    
                    # Close AI assistant modal
                    close_ai_button = page.locator("button:has-text('Close'), button:has-text('×')")
                    if close_ai_button.is_visible():
                        close_ai_button.click()
                        print("AI assistant modal closed")
            else:
                print("AI Assistant modal did not open")
        else:
            print("AI/ML Assistant button not found")
    
    # Always pass the test for now - we're just debugging
    assert True
