#!/usr/bin/env python3
"""Reject commit messages that do not follow Conventional Commits.

Invoked by pre-commit as a `commit-msg` stage hook. Reads the commit
message file path from argv[1] (the pre-commit contract for commit-msg
hooks) and exits non-zero if the subject line does not match a
Conventional Commits shape.

Accepted types (matches types already used in this repo's log):

    feat, fix, chore, docs, test, refactor, perf, build, ci, style, revert

Format: <type>(<scope>)?!?: <subject>

Examples of passing subjects:
    feat: add registry extract agent
    fix(workflow): fork-safe DB pool
    chore(release): v5.3.0 Callisto
    feat!: rename agent_prompts schema
    test(scripts): unit tests for prompt traceability

Examples of failing subjects:
    update things                      # no type
    Feat: capitalized type             # type must be lowercase
    feature: not an accepted type      # use `feat`
    feat:no space after colon          # space required

Special cases handled:
    - Merge commits (auto-generated by git) are always allowed.
    - Revert commits (`Revert "..."`) are always allowed.
    - Fixup commits (`fixup!`, `squash!`) are always allowed; they are
      consumed by `git rebase --autosquash` and never land in history.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Pattern is deliberately strict on the shape but permissive on the subject
# text. Trailer lines and body are not checked.
CONVENTIONAL_RE = re.compile(
    r"^(feat|fix|chore|docs|test|refactor|perf|build|ci|style|revert)"
    r"(\([^)]+\))?!?: .+"
)

BYPASS_PREFIXES = (
    "Merge ",
    "Revert ",
    "fixup! ",
    "squash! ",
    "amend! ",
)


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print("check_commit_msg: expected commit message path as argv[1]", file=sys.stderr)
        return 2

    msg_path = Path(argv[1])
    if not msg_path.is_file():
        print(f"check_commit_msg: commit message file not found: {msg_path}", file=sys.stderr)
        return 2

    lines = msg_path.read_text(encoding="utf-8").splitlines()
    # Skip leading blank lines and git-added comments (`# Please enter...`).
    subject = next(
        (line for line in lines if line and not line.startswith("#")),
        "",
    )

    if not subject:
        print("check_commit_msg: commit message is empty", file=sys.stderr)
        return 1

    if subject.startswith(BYPASS_PREFIXES):
        return 0

    if CONVENTIONAL_RE.match(subject):
        return 0

    print(
        "check_commit_msg: commit subject does not follow Conventional Commits.\n"
        f"  Got:      {subject!r}\n"
        "  Expected: <type>(<scope>)?!?: <subject>\n"
        "  Types:    feat, fix, chore, docs, test, refactor, perf, build, ci, style, revert\n"
        "  Examples: 'feat: add Triton sub-agent'\n"
        "            'fix(workflow): fork-safe DB pool'\n"
        "            'chore(release): v5.4.0 Triton'",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
