"""
Regression test: every agent model/provider selector must render Provider and
Model side-by-side in a 2-column grid (`grid grid-cols-2 gap-3`) with the
canonical dark-gray select classes and the three provider branches
(lmstudio/openai/anthropic) preserved.

Guards the 2026-04 UI unification pass. A future edit that drops an id,
onchange handler, data-agent-prefix wrapper, or grid container would break
JS wiring silently -- this test catches it at the markup level.

Since the provider/model selectors are generated by a shared Jinja2 macro
(components/provider_model_macros.html), the test renders the macro through
Jinja2 and inspects the output HTML.
"""

import re
from pathlib import Path

import pytest
from jinja2 import Environment, FileSystemLoader

TEMPLATE_DIR = Path(__file__).resolve().parents[2] / "src" / "web" / "templates"
WORKFLOW_TEMPLATE = TEMPLATE_DIR / "workflow.html"

# Every agent prefix whose card must match the unified side-by-side style.
# Rank Agent (rankagent) is JS-rendered in the same file and covered separately.
# OS Detection uses a different structure (embedding + fallback model).
AGENT_PREFIXES = [
    "rankqa",
    "cmdlineextract",
    "cmdlineqa",
    "proctreeextract",
    "proctreeqa",
    "huntqueriesextract",
    "huntqueriesqa",
    "registryextract",
    "registryqa",
    "servicesextract",
    "servicesqa",
    "scheduledtasksextract",
    "scheduledtasksqa",
]

# Macro call parameters for each agent, matching the actual workflow.html invocations.
AGENT_MACRO_PARAMS = {
    "rankqa": ("rankqa", "RankAgentQA_provider", "RankAgentQA", False, True),
    "cmdlineextract": ("cmdlineextract", "CmdlineExtract_provider", "CmdlineExtract_model", True, True),
    "cmdlineqa": ("cmdlineqa", "CmdLineQA_provider", "CmdLineQA", False, False),
    "proctreeextract": ("proctreeextract", "ProcTreeExtract_provider", "ProcTreeExtract_model", True, True),
    "proctreeqa": ("proctreeqa", "ProcTreeQA_provider", "ProcTreeQA", False, False),
    "huntqueriesextract": ("huntqueriesextract", "HuntQueriesExtract_provider", "HuntQueriesExtract_model", True, True),
    "huntqueriesqa": ("huntqueriesqa", "HuntQueriesQA_provider", "HuntQueriesQA", False, False),
    "registryextract": ("registryextract", "RegistryExtract_provider", "RegistryExtract_model", True, True),
    "registryqa": ("registryqa", "RegistryQA_provider", "RegistryQA", False, False),
    "servicesextract": ("servicesextract", "ServicesExtract_provider", "ServicesExtract_model", True, True),
    "servicesqa": ("servicesqa", "ServicesQA_provider", "ServicesQA", False, False),
    "scheduledtasksextract": ("scheduledtasksextract", "ScheduledTasksExtract_provider", "ScheduledTasksExtract_model", True, True),
    "scheduledtasksqa": ("scheduledtasksqa", "ScheduledTasksQA_provider", "ScheduledTasksQA", False, False),
}

# Canonical dark-gray select class that every provider/model input must carry.
DARK_SELECT_TOKENS = (
    "dark:bg-gray-700",
    "dark:text-white",
    "rounded-md",
    "font-mono",
    "text-xs",
)


@pytest.fixture(scope="module")
def jinja_env() -> Environment:
    return Environment(loader=FileSystemLoader(str(TEMPLATE_DIR)))


@pytest.fixture(scope="module")
def rendered_blocks(jinja_env) -> dict[str, str]:
    """Render each agent's provider_model_grid macro and return a dict of prefix -> HTML."""
    macro_tmpl = jinja_env.from_string(
        '{% from "components/provider_model_macros.html" import provider_model_grid %}'
        "{{ provider_model_grid(prefix, provider_key, model_key, has_fallback=has_fallback, validate=validate) }}"
    )
    result = {}
    for prefix, params in AGENT_MACRO_PARAMS.items():
        result[prefix] = macro_tmpl.render(
            prefix=params[0],
            provider_key=params[1],
            model_key=params[2],
            has_fallback=params[3],
            validate=params[4],
        )
    return result


@pytest.fixture(scope="module")
def workflow_raw_text() -> str:
    """Raw workflow.html for checks that must inspect the template source."""
    return WORKFLOW_TEMPLATE.read_text()


@pytest.mark.unit
class TestModelSelectorLayoutConsistency:
    """Each sub-agent selector must match the unified card layout."""

    @pytest.mark.parametrize("prefix", AGENT_PREFIXES)
    def test_provider_select_exists(self, rendered_blocks, prefix):
        assert f'id="{prefix}-provider"' in rendered_blocks[prefix], (
            f"Missing provider select for '{prefix}'"
        )

    @pytest.mark.parametrize("prefix", AGENT_PREFIXES)
    def test_side_by_side_grid_wraps_provider(self, rendered_blocks, prefix):
        assert "grid grid-cols-2 gap-3" in rendered_blocks[prefix], (
            f"Selector '{prefix}' is not inside a 'grid grid-cols-2 gap-3' container "
            f"-- Provider/Model should render side-by-side."
        )

    @pytest.mark.parametrize("prefix", AGENT_PREFIXES)
    def test_all_three_provider_branches_present(self, rendered_blocks, prefix):
        block = rendered_blocks[prefix]
        for provider in ("lmstudio", "openai", "anthropic"):
            needle = f'data-agent-prefix="{prefix}" data-provider="{provider}"'
            assert needle in block, (
                f"Selector '{prefix}' missing data-agent-prefix wrapper for provider '{provider}'"
            )

    @pytest.mark.parametrize("prefix", AGENT_PREFIXES)
    def test_provider_and_model_labels_present(self, rendered_blocks, prefix):
        block = rendered_blocks[prefix]
        label_matches = re.findall(
            r'class="block text-\[10px\][^"]*">(Provider|Model)</label>', block
        )
        assert "Provider" in label_matches and "Model" in label_matches, (
            f"Selector '{prefix}' is missing the 'Provider' and/or 'Model' column labels. "
            f"Found: {label_matches}"
        )

    @pytest.mark.parametrize("prefix", AGENT_PREFIXES)
    def test_provider_select_uses_dark_gray_style(self, rendered_blocks, prefix):
        block = rendered_blocks[prefix]
        m = re.search(
            rf'<select[^>]*id="{prefix}-provider"[^>]*class="([^"]+)"', block
        )
        assert m, f"Could not locate class on {prefix}-provider <select>"
        cls = m.group(1)
        for token in DARK_SELECT_TOKENS:
            assert token in cls, (
                f"'{prefix}-provider' select missing '{token}' -- should use unified dark-gray style. Got: {cls}"
            )

    @pytest.mark.parametrize("prefix", AGENT_PREFIXES)
    def test_onchange_handler_calls_onAgentProviderChange(self, rendered_blocks, prefix):
        """Provider select must wire up onAgentProviderChange with the right prefix."""
        block = rendered_blocks[prefix]
        expected = f"onAgentProviderChange('{prefix}')"
        assert expected in block, (
            f"'{prefix}-provider' select missing onchange handler '{expected}'"
        )

    @pytest.mark.parametrize("prefix", AGENT_PREFIXES)
    def test_model_select_has_correct_id(self, rendered_blocks, prefix):
        """LMStudio model select must use {prefix}-model as its id."""
        assert f'id="{prefix}-model"' in rendered_blocks[prefix]

    @pytest.mark.parametrize("prefix", AGENT_PREFIXES)
    def test_openai_input_has_correct_id(self, rendered_blocks, prefix):
        """OpenAI model input must use {prefix}-model-openai as its id."""
        assert f'id="{prefix}-model-openai"' in rendered_blocks[prefix]

    @pytest.mark.parametrize("prefix", AGENT_PREFIXES)
    def test_anthropic_input_has_correct_id(self, rendered_blocks, prefix):
        """Anthropic model input must use {prefix}-model-anthropic as its id."""
        assert f'id="{prefix}-model-anthropic"' in rendered_blocks[prefix]


@pytest.mark.unit
class TestMacroUsedInWorkflowTemplate:
    """Verify workflow.html imports and calls the macro for each agent."""

    def test_macro_import_present(self, workflow_raw_text):
        assert "provider_model_macros.html" in workflow_raw_text, (
            "workflow.html must import from components/provider_model_macros.html"
        )

    @pytest.mark.parametrize("prefix", AGENT_PREFIXES)
    def test_macro_call_present(self, workflow_raw_text, prefix):
        """Each agent must have a provider_model_grid macro call with its prefix."""
        assert f"provider_model_grid('{prefix}'" in workflow_raw_text, (
            f"workflow.html missing provider_model_grid call for '{prefix}'"
        )


@pytest.mark.unit
class TestExtractAgentFallbackOption:
    """Extract agents (not QA) must have the fallback model option."""

    EXTRACT_PREFIXES = [
        "cmdlineextract", "proctreeextract", "huntqueriesextract",
        "registryextract", "servicesextract", "scheduledtasksextract",
    ]
    QA_PREFIXES = [
        "rankqa", "cmdlineqa", "proctreeqa", "huntqueriesqa",
        "registryqa", "servicesqa", "scheduledtasksqa",
    ]

    @pytest.mark.parametrize("prefix", EXTRACT_PREFIXES)
    def test_extract_agent_has_fallback(self, rendered_blocks, prefix):
        assert "Use Extract Agents Fallback Model" in rendered_blocks[prefix], (
            f"Extract agent '{prefix}' must have fallback model option"
        )

    @pytest.mark.parametrize("prefix", QA_PREFIXES)
    def test_qa_agent_has_no_fallback(self, rendered_blocks, prefix):
        assert "Use Extract Agents Fallback Model" not in rendered_blocks[prefix], (
            f"QA agent '{prefix}' should NOT have fallback model option"
        )
