"""Tests for scripts/check_commit_msg.py.

The script is a pre-commit `commit-msg` stage hook. Its contract is:

- Read argv[1] as the path to a file containing the proposed commit message.
- Exit 0 if the subject line follows Conventional Commits OR is a
  git-generated bypass line (Merge / Revert / fixup! / squash! / amend!).
- Exit 1 on a real Conventional Commits violation.
- Exit 2 on a caller contract violation (bad argv, missing file).

These tests pin the regex accept/reject set, the bypass list, and the
handling of comment-only or whitespace-only commit message files (which
git produces when the user aborts by clearing the editor). All are pure
unit tests.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

pytestmark = pytest.mark.unit

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SCRIPT_PATH = REPO_ROOT / "scripts" / "check_commit_msg.py"


def _load_script_module():
    spec = importlib.util.spec_from_file_location("check_commit_msg", SCRIPT_PATH)
    assert spec and spec.loader, f"Cannot load script spec from {SCRIPT_PATH}"
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def script():
    return _load_script_module()


def _write_msg(tmp_path: Path, text: str) -> Path:
    msg_path = tmp_path / "COMMIT_EDITMSG"
    msg_path.write_text(text, encoding="utf-8")
    return msg_path


# ---------------------------------------------------------------------------
# Accept: subjects that MUST pass.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "subject",
    [
        "feat: add registry extract agent",
        "fix(workflow): fork-safe DB pool",
        "chore(release): v5.3.0 Callisto",
        "feat!: rename agent_prompts schema",
        "feat(scope)!: breaking scoped change",
        "test(scripts): unit tests for prompt traceability",
        "docs: update AGENTS.md release section",
        "refactor: extract helper",
        "perf: reduce allocations in hot path",
        "build: bump pinned dep",
        "ci: add release workflow",
        "style: reformat",
        "revert: undo bad commit",
    ],
)
def test_accepts_valid_conventional_commit(script, tmp_path, subject):
    msg = _write_msg(tmp_path, subject + "\n\nOptional body line.\n")
    assert script.main(["check_commit_msg.py", str(msg)]) == 0


# ---------------------------------------------------------------------------
# Reject: subjects that MUST fail with exit 1.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "subject,reason",
    [
        ("update things", "no type prefix"),
        ("Feat: capitalized type", "type must be lowercase"),
        ("feature: not an accepted type", "feature is not in the accepted list"),
        ("feat:no space after colon", "missing space after colon"),
        ("feat add thing", "missing colon"),
        ("feat(: empty scope", "malformed scope"),
        ("feat: ", "empty subject after colon"),
        ("chore(release) v5.3.0", "missing colon after scope"),
    ],
)
def test_rejects_non_conventional_subject(script, tmp_path, subject, reason):
    msg = _write_msg(tmp_path, subject + "\n")
    assert script.main(["check_commit_msg.py", str(msg)]) == 1, reason


# ---------------------------------------------------------------------------
# Bypass: subjects that MUST pass without Conventional Commits shape.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "subject",
    [
        "Merge branch 'dev-io' into main",
        "Merge pull request #123 from fork/topic",
        'Revert "feat: bad idea"',
        "fixup! feat: earlier commit",
        "squash! fix: earlier commit",
        "amend! refactor: earlier commit",
    ],
)
def test_bypasses_generated_subjects(script, tmp_path, subject):
    msg = _write_msg(tmp_path, subject + "\n")
    assert script.main(["check_commit_msg.py", str(msg)]) == 0


# ---------------------------------------------------------------------------
# Empty / comment-only / whitespace-only messages.
# ---------------------------------------------------------------------------


def test_empty_file_is_rejected(script, tmp_path):
    msg = _write_msg(tmp_path, "")
    assert script.main(["check_commit_msg.py", str(msg)]) == 1


def test_comments_only_is_rejected(script, tmp_path):
    # Simulates an aborted commit: user cleared the template, leaving only
    # git-added `# Please enter...` scaffolding.
    msg = _write_msg(
        tmp_path,
        "# Please enter the commit message for your changes.\n# Lines starting with '#' will be ignored.\n",
    )
    assert script.main(["check_commit_msg.py", str(msg)]) == 1


def test_blank_leading_lines_are_skipped(script, tmp_path):
    # Some tooling prepends blank lines; the real subject is still picked up.
    msg = _write_msg(tmp_path, "\n\n# comment\nfeat: real subject\n")
    assert script.main(["check_commit_msg.py", str(msg)]) == 0


# ---------------------------------------------------------------------------
# Caller contract violations.
# ---------------------------------------------------------------------------


def test_missing_argv_returns_exit_2(script):
    assert script.main(["check_commit_msg.py"]) == 2


def test_missing_file_returns_exit_2(script, tmp_path):
    missing = tmp_path / "does_not_exist"
    assert script.main(["check_commit_msg.py", str(missing)]) == 2
